### ISSUE TITLE
Add Index page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#1]
# User Interface

- [x] #82
- [x] #70
- [x] #73
- [x] #78
- [x] #79
- [x] #80

# Screenshots
![Index page mobile](https://user-images.githubusercontent.com/196445/109324506-d07fd280-7865-11eb-9601-fbe017ae786e.png)
![Index page desktop](https://user-images.githubusercontent.com/196445/109324496-cd84e200-7865-11eb-95e1-840e5a50435d.png)

**Comment by Mary-Plashchynskaya** [comment]
![Main page](https://user-images.githubusercontent.com/75125963/100751031-24098e00-33e7-11eb-95f1-e900ef197879.png)

**Comment by lautsevich** [comment]
Looks nice.

A couple of comments from me:

- [ ] Add to the header Search (button) and Wish List (link) icons
- [ ] Add to the main carousel crossed old price
- [ ] Increse the news heading font size to 14px
- [ ] Increse the product card heading font size to 14px
- [ ] Add to the product card crossed old price
- [ ] Think about a long heading for the product card
- [ ] Rename "Categories" heading to "Featured categoies"
- [ ] Rename the "Eco-friendly products" category to "Eco-friendly"
- [ ] Add to the footer the following info:
- - [ ] Payment methods block with PayPal and Visa logos
- - [ ] Phone number, address, email
- - [ ] Additional navigation (Privacy policy, Refund, Payment, Delivery)

**Comment by Mary-Plashchynskaya** [comment]
![Main page 3:12:20](https://user-images.githubusercontent.com/75125963/100996924-f729b800-3559-11eb-80a9-845332987989.png)

**Comment by lautsevich** [comment]
It's much better now. But I have a couple of new comments:

## Header
- [ ] Reorder header buttons to the following:  Search, Wish List, Cart
- [ ] Remove payment methods heading

## Footer
- [ ] Add shop logo
- [ ] Add text block for the website description
- [ ] Add Pinterest icon to the Social Media block
- [ ] Add Maestro, Mastercard, LBL payment logos
- [ ] Make footer navigation like this:
- Information
  - About us
  - Customer Service
  - News
  - FAQs
  - Contact us
- Service
  - Shipping Policy
  - Returns & Refunds
  - Payment Method
  - Terms & Conditions
  - Privacy Policy

## A couple of footer examples

![image](https://user-images.githubusercontent.com/196445/100998309-64dedf80-356c-11eb-9da2-f8b10d18d5a9.png)

![image](https://user-images.githubusercontent.com/196445/100998390-82ac4480-356c-11eb-9aa4-9a4b46d67b43.png)

![image](https://user-images.githubusercontent.com/196445/100998473-9eafe600-356c-11eb-9531-c734d5306336.png)

**Comment by Mary-Plashchynskaya** [comment]
![main page 03:12:20](https://user-images.githubusercontent.com/75125963/101090187-89f84000-35b6-11eb-84b3-92d9eec38d9f.png)

**Comment by Mary-Plashchynskaya** [comment]
![Index page 04:12:20](https://user-images.githubusercontent.com/75125963/101193447-e150eb80-365c-11eb-9974-8a886c38d62d.png)
