### ISSUE TITLE
Add Contact Us page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#193]

**Comment by lautsevich** [comment]
@antalikavasilkova, the frontend isn't assembled. Please fix this so I can review the page.

**Comment by Natalliya-kulva** [comment]
Нужно перейти на jq, но есть ряд нюансов, из-за которых не могу переписать и протестить:
1. Не работают запросы на отправку контактов, ошибка 500, нужно бы решить вопрос с запросами (oc.request)
2. Видела какой то файл, на flash-message. все на jq, пробовала переписать, но мне нужно на что то заменить это событие $(document).on('ajaxSetup',..., примера  не нашла  
3. Нужен апи ключ для карты, мне не дает включить api без номера карточки
Смержено с develop
