### ISSUE TITLE
mix manifest missing

### ISSUE THREAD

**Issue by bmason** [oc-shopaholic/oc-tailwind-shopaholic-theme#198]
I am using 1.41 and October updated as of 6/19/21.

npm run prod seems fine

![Capturea](https://user-images.githubusercontent.com/147215/122656221-55d90c80-d10d-11eb-860c-3f451bcaf0be.PNG)

when I enable the  theme

![Capture](https://user-images.githubusercontent.com/147215/122656277-ca13b000-d10d-11eb-980b-2916c3412cfd.PNG)

I am operating under XAMPP on Windows 10.

**Comment by igor-tv** [comment]
> ![Capture](https://user-images.githubusercontent.com/147215/122656277-ca13b000-d10d-11eb-980b-2916c3412cfd.PNG)

If you are using the Bootstrap for Shopaholic theme, it is better to write [here](https://github.com/oc-shopaholic/oc-bootstrap-shopaholic-theme)

**Comment by bmason** [comment]
yes,  silly error

thank you
