### ISSUE TITLE
Add Catalog page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#2]
# User Interface

- [x] #82
- [x] #265

# Screenshots
![Catalog](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/978d5ca0-2f66-4bea-8c0c-77ab21d15f94)
![Catalog page desktop](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/b8cf4da8-ac2c-4cf5-b663-fa60ac08bcef)

**Comment by Mary-Plashchynskaya** [comment]
![Uploading Catalog 07:12:20.png…]()

**Comment by Mary-Plashchynskaya** [comment]
![Catalog 8:12:20](https://user-images.githubusercontent.com/75125963/101600474-9f78ca00-39fb-11eb-9746-ca19ed425fa6.png)
