### ISSUE TITLE
Fix all missed states for interactive elements

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#223]
Links, Inputs, Buttons

:link, :hover, :active, :focus, :focus-visible

**Comment by Natalliya-kulva** [comment]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/297a29ba-79b7-40a4-901b-978882788052)
Нужно бы вынести этот элемент в компонент, а то разбросан везде, пока пропустила
