### ISSUE TITLE
Fix broken Terms & Conditions page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#300]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/c4fbe266-342c-47b5-afef-a1728c83651a)

**Comment by Natalliya-kulva** [comment]
https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/pull/311
