### ISSUE TITLE
Fix broken News list

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#302]
Theme UI:
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/7baad5cb-6320-4f1f-a354-0d1f5fba6101)

Dashboard:
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/d6320e19-1d96-4eeb-9fa8-17b5491fc268)

**Comment by igor-tv** [comment]
News is displayed. It is necessary to check the settings of test articles to see if the status is set to Published. The publication date must also be no later than the current date.
