### ISSUE TITLE
Fix non-working adding item to cart

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#316]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/64b8a9bd-3a6a-440b-9838-15c9f93f1b76)

**Comment by Natalliya-kulva** [comment]
https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/pull/327
