### ISSUE TITLE
Change the font weight of the Product name in the Review form

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#319]
Make it bold (500)
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/587095f8-f1cb-4227-ba8d-b71d73c10e63)

**Comment by Natalliya-kulva** [comment]
https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/pull/332
