### ISSUE TITLE
Fix a generic file that is not under Git control

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#333]
Each time after running the front-end building we get:

`/app/themes/lovata-tailwind-shopaholic/assets/vendor/jquery.min.js`

![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/3fa3836d-5a9f-4522-a7d5-cae54a557286)

**Comment by Natalliya-kulva** [comment]
https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/pull/335
