### ISSUE TITLE
Add News page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#40]

**Comment by lautsevich** [comment]
Just one comment from me:

- [ ] Increse the product card heading font size to 14px

**Comment by Mary-Plashchynskaya** [comment]
![News 3:12:20](https://user-images.githubusercontent.com/75125963/100997053-1d4f5800-355a-11eb-80e1-1da8fcfe6d15.png)
