### ISSUE TITLE
Fix cosmetic UI defects

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#404]
1. ![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/40b33a19-c73e-4ac3-b137-d4c3941cf227)

2. ![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/ba01f241-0b3f-466b-8e1a-b6aba26f1424)

3. ![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/658a8595-cd08-4b50-a41d-61071cc51e8a)

4. ![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/b1433e13-b6fe-4203-a83d-ca39fe7dbb78)

**Comment by Natalliya-kulva** [comment]
П4:  нужен  этот ПР https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/pull/391
