### ISSUE TITLE
Fix broken product description block

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#406]
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/3b787d54-2d72-4278-ab02-701679ce011f)

Move it to the appropriate position and make it collapsible as it was earlier.

**Comment by Natalliya-kulva** [comment]
В товаре  описание работает так: если описание помещается в три строки, то оно выводится полностью, если описание не помещается, то появляется кнопка с разворотом
