### ISSUE TITLE
Fix catalog Categories list on the Catalog pages presence, appereance and behavior

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#416]
1. This list must be presented on all levels of the catalog hierarchy including the last one. On the last one, a current item must be plain text, not a link.

2. Make the gaps between items smaller like in the image below.
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/e186605e-2a4c-46ed-a115-cd43f5aa3767)

3. Make the first letter of the block heading capitalized using CSS.

4. Only the link text should be clickable not the whole list item block.

**Comment by Natalliya-kulva** [comment]
П1 на бэк
