### ISSUE TITLE
Fix missed aspect ratio for the product image on the Product page

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#418]

**Comment by Natalliya-kulva** [comment]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/db360218-58b9-4142-811f-7cd9ddf3932a)
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/88b6d625-c472-4913-9c39-48f9eb58e96c)

Мы точно используем aspect ratio ? Не все картинки будут корректно показаны

**Comment by Natalliya-kulva** [comment]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/25d8bb54-c54b-4f61-bb83-c1f67701b05a)
Возможно стоило бы значения как то унифицировать
