### ISSUE TITLE
Fix UI cosmetic bugs

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#430]
1. Fix the Catalog section block view
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/cd81daf2-12d5-4da1-b133-229a00f42396)

2. Remove the rounded corner from the image
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/e3e6bf65-ad17-4d4c-af46-4b8decdf820e)

3. Remove unnecessary underline on hover
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/4307f0b6-aed0-4273-85c2-29bfca52f426)

4. Add hover only in text not the empty space on the right

![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/8bafd3e0-7d1f-42e3-9b53-5aae9d2acee9)

5. Reduce the distance between the top border of the tab and the paragraph (don't touch prose classes) 

![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/99dcf8af-2ee9-42a6-a579-df7f9b871bba)

6. Add spacing (margin bottom) for Product name

![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/41eb8b8b-b55e-4a81-b766-291f09646fd4)

7. Position the Wish List icon and price according to design in Figma

![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/1a6b43d2-d0bb-4c7a-9ca4-49f1bba83169)

8. Fix the UI according to design in Figma (restore missed markup)

![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/3091793d-1267-4bca-bd21-2eafebc3869f)

**Comment by Natalliya-kulva** [comment]
Что бы выполнить пункт 6, нужен ключ для карты
