### ISSUE TITLE
Make the site search functionality work again

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#432]
Try to make the current code workable again. Then we'll see the functionality and write them as a description for future full refactoring

**Comment by Natalliya-kulva** [comment]
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/6d94dd21-fd8d-486a-b463-c226a6f4d4e4)
![image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/33567896/f080aca9-7fcf-4db7-b52e-4ce56416e222)
События починила, но там в ответе поиска всегда приходит пустота.
Код бы почистить и оптимизировать, но в задаче это не стоит
