### ISSUE TITLE
Delivery method description must be hidden by default

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#433]
![Image](https://github.com/oc-shopaholic/oc-tailwind-shopaholic-theme/assets/196445/e55d01e5-44fc-495e-b23d-8cdec73d99ad)

**Comment by Natalliya-kulva** [comment]
Если текст вмещается в одну строку, выпадашка не появляется. Если текста больше чем одна строка, то выпадашка появится
