### ISSUE TITLE
SEO requirements

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#48]

**Comment by lautsevich** [comment]
What document structure will be best for SEO Technical Requirements? Pls, share your ideas!

**Comment by devcustrom** [comment]
1. hyperlinks with empty anchors
2. external links must be nofollow, noopener

**Comment by devcustrom** [comment]
3. cart page must have meta robots noindex, nofollow
4. robots.txt should contain instructions prohibiting indexing of filter pages
5. Lack of horizontal scrolling
6. Loading metrics scripts after loading all components required for display
7. Asynchronous script loading
8. Adding padding for <body> equal to the scrollbar while disabling <body> scrolling
9. <h1> must be one
10. Alt alt images must be filled
11. <h1> must be present on every indexed page
12. internal links should not be nofollow, noopener
13. Server response should not exceed 500ms
14. Using sw.js and an offline page
