### ISSUE TITLE
Add Navigation List with Icon block

### ISSUE THREAD

**Issue by lautsevich** [oc-shopaholic/oc-tailwind-shopaholic-theme#76]

**Comment by Natalliya-kulva** [comment]
Осталось поправить
- catalog и catalog/category страница использует один шаблон. Номинально я вывела категории, но есть сомнения. Нужно не выводить список категорий на странице category или вывести метку с активной страницей 
- в макете явно есть заголовки первого уровня, сейчас их нет на catalog и catalog/category
